name: opencv2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - matplotlib=2.1
  - numpy=1.14
  - pandas=0.22
  - pillow=5.0.0
  - pip=9.0 # not necessary, unless you want to install pip packages, like Keras
  - scikit-image=0.14
  - scipy=1.0
  - opencv=3.3.1
  - ipykernel=4.8 # after instll, activate environment and type python -m ipykernel install --user --name opencv2